name: Update project
on:
  workflow_dispatch:
  schedule:
    - cron: "*/30 * * * *"

jobs:
  add-project:
    name: Update Projects
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - name: Install dependencies
        run: yarn

      - name: Update projects & Build
        run: |
          yarn update-projects
          yarn build

      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
        if: github.ref == 'refs/heads/main'
